version: '3.4'
services:
  nginx:
    ports:
      - 8000:8080
  netbox:
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    image: netbox:latest-plugins
  netbox-worker:
    image: netbox:latest-plugins
