version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
    build: &build
      context: .
      dockerfile: Dockerfile-Plugins
    image: &image netbox:${VERSION-v3.1.7}-plugins
  netbox-worker:
    build: *build
    image: *image
  netbox-housekeeping:
    build: *build
    image: *image
  tls:
    image: caddy:2-alpine
    depends_on:
      - netbox
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80 # Allows for http redirection
      - 443:443
