version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
    build: &build
      context: .
      dockerfile: Dockerfile-Plugins
    image: &image netbox:${VERSION-v3.0.7}-plugins
  netbox-worker:
    build: *build
    image: *image
  netbox-housekeeping:
    build: *build
    image: *image
  tls:
    image: zazukoians/hitch
    environment:
      HITCH_PEM: /app/cert_and_key.pem # path within the container to the TLS certificate
      HITCH_PARAMS: --backend=[netbox]:8080 --frontend=[*]:443 # listen on *:443 and forward traffic to netbox
    depends_on:
      - netbox
    ports:
      - 443:443 # bind the container's port 443 to the host's port 8443
