FROM netboxcommunity/netbox:latest-ldap

COPY ./plugin_requirements.txt /
RUN pip install --no-warn-script-location -r /plugin_requirements.txt
COPY configuration/onboarding.py /opt/netbox/netbox/netbox/onboarding.py