---
version: '3.4'
services:
  netbox:
    ports:
      - 8000:8080
    build: &build
      context: .
      dockerfile: Dockerfile-Plugins
    image: &image gitlab.hpwren.ucsd.edu:5005/systems/netbox-docker:${VERSION-v3.2.1}-plugins
    restart: "unless-stopped"
  netbox-worker:
    build: *build
    image: *image
    restart: "unless-stopped"
  netbox-housekeeping:
    build: *build
    image: *image
  tls:
    image: caddy:2-alpine
    depends_on:
      - netbox
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80 # Allows for http redirection
      - 443:443
    restart: "unless-stopped"
  postgres:
    restart: "unless-stopped"
  redis:
    restart: "unless-stopped"
  redis-cache:
    restart: "unless-stopped"
...

