FROM netboxcommunity/netbox:latest-ldap AS builder

RUN apk add --no-cache \
      build-base \
      libxml2-dev \
      libxslt-dev \
      libffi-dev \
      py3-pip \
      python3-dev \
      && python3 -m venv /opt/venv \
      && /opt/netbox/venv/bin/python3 -m pip install --upgrade pip setuptools

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install -r /plugin_requirements.txt

FROM netboxcommunity/netbox:latest-ldap AS main

RUN apk add --no-cache \
      libxslt

WORKDIR /opt

COPY --from=builder /opt/netbox/venv /opt/netbox/venv

COPY configuration/onboarding.py /opt/netbox/netbox/netbox/onboarding.py
