ARG VERSION=latest
FROM netboxcommunity/netbox:${VERSION}-ldap
ARG VERSION

RUN apk add --no-cache \
      build-base \
      libxml2-dev \
      libxslt-dev \
      libffi-dev \
      py3-pip \
      python3-dev\
      git
#      && python3 -m venv /opt/netbox/venv \
#      && /opt/netbox/venv/bin/python3 -m pip install --upgrade pip setuptools

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install --no-warn-script-location -r /plugin_requirements.txt

COPY configuration/onboarding.py /etc/netbox/config/onboarding.py
RUN SECRET_KEY="dummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input

WORKDIR /opt/netbox/netbox
